In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn.neighbors
import scipy
from scipy import ndimage
import importlib
import itertools
from skimage import io

import avul
from TestDataset import ImList

In [ ]:
importlib.reload(avul)

In [2]:
StabCrit = 4
ActLevels = []
seaRs = []
TestActLevels = []
TestseaRs = []
from IPython.core.debugger import set_trace
for x in range(9):
    Im = ImList[x]
    #get the five biggest connected components in the image
    labels_out, tra = ndimage.measurements.label(Im,structure=np.ones((3,3,3)))
    FlLab = np.ravel(labels_out)
    FlLab = FlLab[np.nonzero(FlLab)]
    if FlLab.size>0:
        u, indices = np.unique(FlLab, return_inverse=True)
        BigComLab = u[np.argmax(np.bincount(indices))]
        ComIm = labels_out * (labels_out == BigComLab)
        print(np.flatnonzero(ComIm).size)
        #Run stablesteps
        FiltIm = avul.comfilt(ComIm)
        #pdb.set_trace()
        points = avul.getpoints(FiltIm)

        CurActLevels, CurseaR, EnPts1 = avul.stbsteps(points,StabCrit)
        print(CurActLevels)
        print(EnPts1)
        #set_trace()
        ActLevels.append(CurActLevels)
        seaRs.append(CurseaR)
        #np.savetxt('test'+ str(x) + 'BigComFiltV2NewImp' +'.pts',points,fmt='%1i',delimiter=' ')


319605
5
[24 25 30 33 34]
207373
2
[24 34]
52979
3
[ 7 15 34]
113242
7
[ 5  9 15 17 19 30 34]
61959
1
[34]
281179
1
[34]
498680
1
[34]
212852
1
[34]
255751
3
[13 32 34]


In [3]:
ActLevels

[5, 2, 3, 7, 1, 1, 1, 1, 3]